from pathlib import Path

# Caminhos
ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'calculadora.png'


# Cores
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'


# Tamanhos
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 30
SMALL_FONT_SIZE = 18
TEXTE_MARGIN = 15
MINIMUM_WIDTH = 500
